### ISSUE TITLE
index.php redirect

### ISSUE THREAD

**Issue by michail1982** [Waavi/translation#100]
initialy i got url /index.php?1=1
TranslationMiddleware convert it to /index.php/ru/index.php?1=1 fnd redirect client
gues what happends on next request?  /index.php/ru/index.php/ru/index.php?1=1

error in parseUrl  method of UriLocalizer ?

**Comment by sildraug** [comment]
Since you are using the second segment of the url for the locale, you will need to use localize:2 in your middleware, for example:

\Route::get('/en', ['middleware' => 'localize:2', function () {
            return 'Hello world';
        }]);
