### ISSUE TITLE
Interface 'Illuminate\Translation\LoaderInterface' not found

### ISSUE THREAD

**Issue by atudz** [Waavi/translation#105]
When migrating from laravel 5.4 to 5.5 I got this error. Base from their spec doc it says 

"The Illuminate\Translation\LoaderInterface interface has been moved to  Illuminate\Contracts\Translation\Loader."

**Comment by xakzona** [comment]
Because where is no support for Laravel 5.5 yet

**Comment by atudz** [comment]
@xakzona  when can we expect for the support of Laravel 5.5?

**Comment by sildraug** [comment]
Support has been added on branch 2.3
