### ISSUE TITLE
 Class translation.cache.repository does not exist

### ISSUE THREAD

**Issue by vov4ik08** [Waavi/translation#108]
Hello. I use laravel 5.5, after install waavi/translation 2.3.x and try to appla publish command i see error
$ php artisan vendor:publish --provider="Waavi\Translation\TranslationServiceProvider"

  [ReflectionException]
  Class translation.cache.repository does not exist

Please help me.

**Comment by sildraug** [comment]
Tried on a fresh install of laravel 5.5 and it worked fine. Here is what I did:

```
laravel new fresh
cd fresh
composer require waavi/translation
php artisan vendor:publish --provider="Waavi\Translation\TranslationServiceProvider"
```

Did not get any errors.
