### ISSUE TITLE
Unnesessary checks

### ISSUE THREAD

**Issue by michail1982** [Waavi/translation#111]
https://github.com/Waavi/translation/blob/master/src/TranslationServiceProvider.php#L76
is query db on each request on pruduction environment. WTF?

**Comment by andersLAL** [comment]
I agree, this does not seem like a good design. In my case at least, these are pretty slow database queries as well.

I assume it's related to https://github.com/Waavi/translation/issues/104, but there must be a better way to handle that? For example making a note in the documentation that when adding the package to an existing project, use files as the source until migrations are completed? I had the same issue when I started using the package, but just performed the migrations manually, also no big problem.
