### ISSUE TITLE
Redundant getStatusCode() calls in tests

### ISSUE THREAD

**Issue by kkomelin** [Waavi/translation#116]
https://github.com/Waavi/translation/blob/c89d1023cef62f26c2cbc431511fd8c08af69617/tests/Middleware/TranslationMiddlewareTest.php#L66

**Comment by kkomelin** [comment]
@sildraug It would be great if you somehow motivated your actions.

```php
        $statusCode = $response->getStatusCode();
        $this->assertEquals(200, $response->getStatusCode());
```
Why do you need to call getStatusCode() twice?

**Comment by sildraug** [comment]
@kkomelin This is not an issue. A pull request is welcome if it bothers you.

**Comment by kkomelin** [comment]
@sildraug Thanks for your reply. Good luck.
