### ISSUE TITLE
config:cache ErrorException

### ISSUE THREAD

**Issue by saidbakr** [Waavi/translation#119]
In Laravel 5.4 I have used composer to install version 2.2.x. After replacing `Illuminate\Translation\TranslationServiceProvider::class,` with `Waavi\Translation\TranslationServiceProvider::class,` and trying to run `php artisan config:cache` I got the following error:

> [ErrorException]                                                             
>   file_put_contents(/home/said/www/factory/storage/framework/cache/data/16/2c  
>   /162c7017cfee4ca3aaa3889fbe3d9a960f4fddfe): failed to open stream: No such   
>   file or directory  

I tried `config:clear` but It could not solve this issue. The rest steps does not work too.

**Comment by xakzona** [comment]
php artisan cache:clear
