### ISSUE TITLE
2.2.2 with Laravel 5.4 - too many redirects

### ISSUE THREAD

**Issue by philippkreis** [Waavi/translation#125]
Hi there,

after installing and setting the global middleware, I tried to open a page.
Chrome runs into "TOO_MANY_REDIRECTS" and the url concatinates the language string.

http://192.168.1.222:8888/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de/de

Did you see this before? Any thoughts?

Thanks,
Philipp

**Comment by sildraug** [comment]
You need to configure your available locales in the config file. German is not an available locale by default. Once that's done it should work fine.
