### ISSUE TITLE
Parse error: syntax error, unexpected 'Trait' (T_TRAIT), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by ngima** [Waavi/translation#133]
I am trying to use Model attributes translation according to Documentation. But unfortunately I got this `Parse error: syntax error, unexpected 'Trait' (T_TRAIT), expecting identifier (T_STRING)` error. 
![screenshot from 2018-05-01 16-02-00](https://user-images.githubusercontent.com/23276565/39469644-01c72b1c-4d59-11e8-9a73-30156d1979c6.png)

**Comment by Kindamba** [comment]
It seems like the path should be changed to something like this Waavi\Translation\Traits\Translatable; instead of \Waavi\Translation\Translatable\Trait; that work for me.

**Comment by jackohjin** [comment]
Trait is a reserve php keyword, so use Traits instead of Trait will solve the problem.
