### ISSUE TITLE
Load language file in folders recursively

### ISSUE THREAD

**Issue by rjrg1989** [Waavi/translation#14]
How can I add the possibility to load language files recursively, lets assume that in my language folder  I have another folder like /users or /posts and i want to load those files to the database and retrieve them later
I have not gone deep in the code but i believe it should not be difficult, anyway, I´ll apreciate the help...
rjrg1989

**Comment by Tavicu** [comment]
If anyone still looking for this i made some changes to load files from folders too.

https://github.com/Tavicu/translation

**Comment by sildraug** [comment]
This feature has been implemented on our latest release.
