### ISSUE TITLE
Support for Laravel 7.0 ？

### ISSUE THREAD

**Issue by mogody** [Waavi/translation#173]

**Comment by saeednikookalam** [comment]
Hi
Yes, use the below composer command

composer require waavi/translation 2.4.x

**Comment by JoNMii** [comment]
- Can only install one of: laravel/framework[5.5.x-dev, v7.10.3].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.10.3].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.10.3].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.10.3].
    - Installation request for laravel/framework (locked at v7.10.3, requi

**Comment by dmitryuk** [comment]
I'm using the package with Laravel 7 without problems
