### ISSUE TITLE
Support for Laravel 8.0?

### ISSUE THREAD

**Issue by cstriuli** [Waavi/translation#177]

**Comment by cstriuli** [comment]
Check PR #178

**Comment by EmilMoe** [comment]
Nothing changed for 7 months, I could fear this project is dead?

**Comment by gulios** [comment]
any update ?

**Comment by dmitryuk** [comment]
Owners of the package are silent

**Comment by dereksdev** [comment]
package appears to be abandoned...

**Comment by krychu90** [comment]
Any fork working with Laravel 8?
