### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by CedNet** [Waavi/translation#26]
Hi! Your language package seems to be great! Will you add support for Laravel 5 now that the code appears stable and about to be released? Would be awesome.

**Comment by bjora857** [comment]
Yes, would love to see Laravel 5 support.

**Comment by Aeonax** [comment]
It would be awesome to have this working for Laravel 5. My work project is still running Laravel 4 and we use the databased translations extensively.

**Comment by jamesalways** [comment]
Hi! 

We are working it! 

Best!

**Comment by sebastiaanluca** [comment]
@jamesalways Any ETA? Might need this for a new project.

**Comment by sildraug** [comment]
@Aeonax We just released a Laravel 5 version. It is still under testing, but it is much more throughly tested than the previous one and comes with some nice new features.
