### ISSUE TITLE
Unable to translate text to another language

### ISSUE THREAD

**Issue by bczm8703** [Waavi/translation#29]
Hi. I am using Laravel 5.1. i just installed the waavi package and tried with the translation. But it seems that my text is unable to translate to another language other then the default english. On my blade file i did this {{ trans('messages.member login') }}. when the page is loaded, i saw this Member Login which is correct. But when i tried to switch to  locale 'zh_cn' the text should change to it chinese text. the chinese text has already being entered into the DB. when user tried to switch langauge i put the locale into a Session like this Session::put('locale', 'zh_cn'). 
is this wrong?
if wrong how do i swap the locale for the chinese text to be shown?

my config/translator.php looks like this
```
return [

    /*
    |--------------------------------------------------------------------------
    | Default Translation Mode
    |--------------------------------------------------------------------------
    |
    | This option controls the translation's bundle mode of operation.
    |
    | Supported:
    |
    |   'mixed'         Both files and the database are queried for language entries, with files taking priority.
    |   'database'      Use the database as the exclusive source for language entries.
    |   'files'         Use files as the exclusive source for language entries [Laravel's default].
     */
    'source'            => 'database',

    // In case the files source is selected, please enter here the supported locales for your app.
    // Ex: ['en', 'es', 'fr']
    'available_locales' => ['en', 'zh_cn'],

    /*
    |--------------------------------------------------------------------------
    | Default Translation Cache
    |--------------------------------------------------------------------------
    |
    | Choose whether to leverage Laravel's cache module and how to do so.
    |
    |   'enabled'       Boolean value.
    |   'timeout'       In minutes.
    |
     */
    'cache'             => [
        'enabled' => env('TRANSLATION_CACHE_ENABLED', true),
        'timeout' => env('TRANSLATION_CACHE_TIMEOUT', 60),
        'suffix'  => env('TRANSLATION_CACHE_SUFFIX', 'translation'),
    ],
];

```

**Comment by sildraug** [comment]
Hi!

The easiest way to give the user the ability to switch languages is to use the Translation Middleware that's included (https://github.com/Waavi/translation#uri-localization). With this middleware active in your routes, users visiting http://example.com/en/your_url will get the english version and users visiting /zh_cn/your_url will get the Chinese version.

This middleware will also allow you to show the user a menu to switch languages in your blade templates, for example:

```php
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ $currentLanguage->name }} <b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach ($altLocalizedUrls as $alt)
            <li><a href="{{ $alt->url }}" hreflang="{{ $alt->locale }}">{{ $alt->name }}</a></li>
        @endforeach
    </ul>
</li>
```

Both $currentLanguage and $altLocalizedUrls are set automatically by the translation middleware.

To switch languages manually, you must do \Lang::setLocale('zh_ch'), but this will only work for the current request.

If you want to switch languages based on a variable in Session, you will need to register a new Middleware to do so. I'm trying to work on an update that will allow you to do this.

**Comment by bczm8703** [comment]
hi.. i fixed this already.. i created a middleware to set $app->setLocale(Session::get('locale')) .. thx
