### ISSUE TITLE
[L5.2] Call to undefined method ...\Facades\UriLocalizer::localeFromRequest()

### ISSUE THREAD

**Issue by Cyrille37** [Waavi/translation#33]
Hi,

I followed the doc to configuring Waavi\Translation but got a problem with the UriLocalizer facade.
- "laravel/framework": "5.2.22"
- "waavi/translation": "2.1.4"

The code
```
Route::group(['prefix' => \UriLocalizer::localeFromRequest()], function(){
...
```
thrown the Exception:
```
FatalErrorException in Facade.php line 215: Call to undefined method Waavi\Translation\Facades\UriLocalizer::localeFromRequest()
```
I do not understand the error because of course, the Facade & Service exists. So why it does not found the well defined method localeFromRequest() ??

I'm lost...

Cheers, Cyrille.

**Comment by QuibaX** [comment]
@Cyrille37 You can temporarily fix it by creating it yourself.
Ex: `$localizer = \App::make(\Waavi\Translation\UriLocalizer::class);`
And then, as your prefix use: `$localizer->localeFromRequest()`

May not be the best idea, but it could help you for now.

**Comment by aifaiz** [comment]
`$localizer = \App::make(\Waavi\Translation\UriLocalizer::class);`

this works man!

**Comment by dmitrymomot** [comment]
I've got the same error, but solution from @QuibaX doesn't work in my case :(

**Comment by sildraug** [comment]
Please update to version 2.1.4.1 and make sure you've added the UriLocalizer alias to your config/app.php aliases array:

'UriLocalizer'     => Waavi\Translation\Facades\UriLocalizer::class,

Let me know if this helps.

**Comment by thku** [comment]
Still throws the same error…

**Comment by sildraug** [comment]
So neither \UriLocalizer::localeFromRequest() nor \App::make(\Waavi\Translation\UriLocalizer::class)->localeFromRequest() or \App::make('UriLocalizer')->localeFromRequest() work?

This is really odd. Could you try with:

Route::group(['prefix' => UriLocalizer::localeFromRequest()], function(){

that is, without the \ before UriLocalizer?

**Comment by thku** [comment]
OK, this is all very odd:
First, it works, as long as I don't exclude the old workaround:

	// bug fix for Waavi…::localeFromRequest() problem
	$localizer = \App::make(\Waavi\Translation\UriLocalizer::class);
	
	// localized pages
	Route::group(['prefix' => UriLocalizer::localeFromRequest(), 'middleware' => 'localize'], function () {
	…

From the provided solutions, only `\App::make(\Waavi\Translation\UriLocalizer::class)->localeFromRequest()`works.

In addition, but probably only a misconfiguration, it seems that `php artisan translator:load` does not load the languages in the database any more…

**Comment by Uebix** [comment]
I have the same problem...

`FatalErrorException in Facade.php line 215: Call to undefined method Waavi\Translation\Facades\UriLocalizer::localeFromRequest()`

**Comment by cirdog** [comment]
I think I've got similar problem regarding invoking "translation.cache.repository" from Facade, and I solved it by adding the below to the Service Provider:

    public function provides()
    {
        return ['translator', 'translation.loader', 'translation.cache.repository'. 'UriLocalizer'];
    }

Then run, php artisan clear-compiled, and let it regenerates the /bootstrap/cache/services.php

The key to the problem (mine was ReflectionException) is a malformed services.php. Somehow 5.2 looks up class names for instantiation there, so any missing entry would cause a fault. I actually mimicked it from other packages so I guess it's a new requirement for 5.2 maybe?

Please try it out and share your results.

**Comment by sildraug** [comment]
Is anyone still having this issue?

**Comment by thku** [comment]
seems to be fixed
