### ISSUE TITLE
More consistent namespace for UriLocalizer.

### ISSUE THREAD

**Issue by cirdog** [Waavi/translation#39]
Only the UriLocalizer is not following the package's naming convention. I propose to change it to "translation.uri.localizer", and the respective Facade can handle the Name->Instance-Name translation.

    public function register()
    {
        $this->mergeConfigFrom(__DIR__ . '/../config/translator.php', 'translator');

        parent::register();
        $this->registerCacheRepository();
        $this->registerFileLoader();
        $this->registerCacheFlusher();
        $this->app->singleton('translation.uri.localizer', UriLocalizer::class);
        $this->app[\Illuminate\Routing\Router::class]->middleware('localize', TranslationMiddleware::class);
        // Fix issue with laravel prepending the locale to localize resource routes:
        $this->app->bind('Illuminate\Routing\ResourceRegistrar', ResourceRegistrar::class);
    }

    protected static function getFacadeAccessor()
    {
        return 'translation.uri.localizer';
    }

With these, the package's namespace would be consistent inside the bootstrap/cache/services.php

    'translator' => 'App\\Providers\\TranslationServiceProvider',
    'translation.loader' => 'App\\Providers\\TranslationServiceProvider',
    'translation.cache.repository' => 'App\\Providers\\TranslationServiceProvider',
    'translation.uri.localizer' => 'App\\Providers\\TranslationServiceProvider',

Or whatever name you choose that exhibits a more consistent convention, it'd be great!

**Comment by sildraug** [comment]
Done! See v2.1.4.3
