### ISSUE TITLE
Refactor away in_array() for $availableLocales in favor of hashtable (isset)

### ISSUE THREAD

**Issue by cirdog** [Waavi/translation#41]
Reference doc:
http://maettig.com/1397246220

I know that $availableLocales are usually not that many, but if in_array() is inherently slow, this slowness will scale up when the request traffic ramps up.

Then why not just refactor it into isset() (hash table), to make it future-proof?

Thanks for your consideration.

**Comment by sildraug** [comment]
Although I understand what you are saying, this is a really minor issue for us to spend time on. If you really think this should be changed, feel free to make a PR.

Thanks!
