### ISSUE TITLE
Locales > 6 characters aren't allowed

### ISSUE THREAD

**Issue by olestourko** [Waavi/translation#42]
In the database migration script, the locale is limited to 6 characters. This prevents some locales from being used properly, ie, "mn-Mong", "zh-Hant".

**Comment by adamzwakk** [comment]
#43

**Comment by sildraug** [comment]
See v2.1.4.5 for a fix.

You must update to this version, then publish the migration using:

`php artisan vendor:publish --provider="Waavi\Translation\TranslationServiceProvider" --tag="migrations"`

Then finally migrating your database:

`php artisan migrate`
