### ISSUE TITLE
Fails on 'attributes' key?

### ISSUE THREAD

**Issue by jfi** [Waavi/translation#48]
This seems to fail on the following at the bottom of `resources/lang/en/validation.php` when running `translator:load`:

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */

    'attributes' => [],

The value 'Array' is inserted into the database for this key and the following error is thrown:

    [ErrorException]                                                                       
    preg_replace(): Parameter mismatch, pattern is a string while replacement is an array 

Of course, this value can just be removed, but if this is included by default it seems as though it should be able to be handled?

**Comment by sildraug** [comment]
Hi jfi,

I've tested it out and the latest version (2.1.4.6 and onwards) doesn't load empty arrays into the DB. Could you make sure you're on the latest version?
