### ISSUE TITLE
"Class translation.uri.localizer does not exist" using UriLocalizer in route prefix

### ISSUE THREAD

**Issue by mikeu** [Waavi/translation#49]
I am trying to add this translation package to an existing Laravel 5.2 project. I was previously using a different package for localizing just URIs ([Laravel Localization](https://github.com/mcamara/laravel-localization)) but removed it before installing the Waavi translation package. After installing and configuring this package, and adding `'prefix' => UriLocalizer::localeFromRequest()` to my routes, an exception is thrown with the following error:

```
ReflectionException in Container.php line 738:
Class translation.uri.localizer does not exist
```

While attempting to debug the problem I found that when Laravel compiles the manifest of service providers, it creates deferred services for `translator` and `translation.loader` because these are in the array returned by the `provides()` method that the Waavi `TranslationServiceProvider` inherits from `LaravelTranslationServiceProvider`. But the string `translation.uri.localizer` doesn't appear anywhere in my `bootstrap/cache/services.php` file, even after manually deleting it to force a recompilation.

It seems as if the exception is being thrown _before_ the `register()` method of your TranslationServiceProvider is being called, which might be part of the problem, I'm not sure.

Please let me know what else I can try, or what other information/tests would be helpful to resolve this issue. Your translation package looks great, and I'd love to be able to start using it. Thanks!

**Comment by cirdog** [comment]
Hi Mike,

Try adding this to either the vendor's TranslationServiceProvider or to your own subclass of it.

```
    public function provides()
    {
        return array_merge(parent::provides(), ['translation.cache.repository', 'translation.uri.localizer']);
    }
```

This extends the Lavarel's stock TranslationServiceProvider to account for the added services. Please give it a try and be sure to delete services.php just to be safe.

Please let us know the result.

**Comment by mikeu** [comment]
Thanks @cirdog, that seems to have done the trick!

**Comment by sildraug** [comment]
Cirdog's solution was implemented on v.2.1.4.7.

Thank you again!
