### ISSUE TITLE
Can't get locales from translator.php config file

### ISSUE THREAD

**Issue by antoniomadonna** [Waavi/translation#54]
I think there's a naming mismatch between the config file and `LanguageRepository->availableLocales()`.

In `translator.php` the available locales key is named `available_locales`, while in `LanguageRepository` (line 129-130-134) the code tries to access `translator.locales`.

**Comment by sildraug** [comment]
There's no mismatch. If you look at line 134, you'll see that's where we set the translator.locales config variable. This variable is the locales that are configured in the database (so that you don't need to change your config file if you add a language to the DB).

Best!
