### ISSUE TITLE
Always direct back to default locale while go to another page

### ISSUE THREAD

**Issue by ben8889** [Waavi/translation#56]
Hi, I am using laravel 5.2. I did follow all yours document to implement translation feature. But I got an issue, lets say current my url is "something.com/zh/about", when I click to another page it will return back to default locale which is like "something.com/en/gallery". Is there any more setting I need to configure or anything I did wrong? 
Thank you

**Comment by ben8889** [comment]
Hi, I have found the way to solve it.

**Comment by DilithiumVentures** [comment]
Hi i am using Laravel 5.4 and implemented the examples, this works like a charm. Thanks!
One thing doesn't work though and this topic sounds very similar, but doesn't state a solution :-)

Once i change the url to /nl from /en it will load the correct language on the page. But as soon as i navigate to another page, this locale is lost and it defaults back to /en. I have implemented the code, according to the manual, but this doesn't work (and the language switcher throws an exception too).

It feels like the session is non-persistent or something, should it keep track of the locale by default? Or do i need to set it somewhere?
