### ISSUE TITLE
 Non-static method Waavi\Translation\Repositories\LanguageRepository::findByLocale() should not be called statically, assuming $this from incompatible context

### ISSUE THREAD

**Issue by mlinko** [Waavi/translation#57]
I run this code in my controller

Top of my controller

```
use Waavi\Translation\Repositories\LanguageRepository;
use Waavi\Translation\Repositories\TranslationRepository;

```
function that runs

```
public function give(){
$language = LanguageRepository::findByLocale(1);
}
```
it says 

Non-static method Waavi\Translation\Repositories\LanguageRepository::findByLocale() should not be called statically, assuming $this from incompatible context.

**Comment by sildraug** [comment]
Those methods are not static. From the controller, if on the latest version of Laravel, you can leverage the IOC to use the repos like so:

```php
public function give(LanguageRepository $repo) {
   $language = $repo->findByLocale(1);
}
```

Alternatively:
```php
public function give(){
   $repo = \App::make(LanguageRepository::class);
   $language = $repo->findByLocale(1);
}
```
