### ISSUE TITLE
Settings App::locale

### ISSUE THREAD

**Issue by jvlierop** [Waavi/translation#58]
When using the URI Localization the app locale is not set in the middleware. Only the translator locale is set. When using the URI Localization as locale determination it would be nice to set the App locale in the middleware. 

I fixed this issue for a current application by setting the app locale in the main controller
` public function __construct(Translator $translator)
    {
        App::setLocale($translator->locale());
    }
`

**Comment by sildraug** [comment]
This should be fixed in 2.1.4.9. Thank you!
