### ISSUE TITLE
Breaking change in 2.1.4.10

### ISSUE THREAD

**Issue by nickescobedo** [Waavi/translation#59]
If the repo is following the semantic versioning then commit 97bfbc3 should be considered a breaking change. The commit breaks apps that use locale in the session differently than a string.

For example I have an app which we place a locale object in the session and not the string. This breaks our app because our app expects an object, but a string is placed automatically by the commit mentioned above.

An if conditional could be added on line 72 for b6e24d5 checking for a config which would tell the TranslationMiddleware whether or not to set the locale.

**Comment by sildraug** [comment]
You are completely right. I've changed the session variable name so that is much more specific to the package, you shouldn't see any collisions now. Please let me know if this works for you.

Best!

**Comment by nickescobedo** [comment]
Thank you @sildraug! 😄
