### ISSUE TITLE
It's not possible to edit other attributes of translation

### ISSUE THREAD

**Issue by Numline1** [Waavi/translation#60]
Hi,

first of all, great package, really enjoying it in our product.

I was wondering, why don't the TranslationRepository methods update() and updateAndLock() accept $attributes array similar to LanguageRepository. Only accepting $id and $text makes it impossible for the user to update stuff like namespace etc.

Maybe I misunderstood the purpose of it, anyhow, it got me wondering.

Thanks!

**Comment by sildraug** [comment]
Hi @Numline1 ,

Database entries are supposed to be imported from your language files, and the update method is useful for allowing live text changes to be made without having to change the code. updateAndLock will also protected the entry from being overwritten the next time you import your language files into the DB.

Hope this helps!
