### ISSUE TITLE
Dots in translations

### ISSUE THREAD

**Issue by nepster-web** [Waavi/translation#61]
Hello. I use your extension translation and my translations have dots.

Example:
```php
    'product' => 'Товар',
    'products' => 'Товары',
    'products.control' => 'Управление товарами',
    'products.all' => 'Все товары',
    'products.create' => 'Создать товар',
    'products.add' => 'Добавить товар',
    'products.edit' => 'Редактировать товар',
    'products.update' => 'Обновить товар',
    'products.delete' => ' Удалить товар',
    'products.file_help' => 'Добавить файлы к товару'
```

In test environment I used the driver **files**. After that, I switched the driver to **database** and an error occurred. 

This query: https://github.com/Waavi/translation/blob/master/src/Repositories/TranslationRepository.php#L235 return all records but collection method reduce use **array_set**.

Function array_set use dot for specific purposes: https://github.com/illuminate/support/blob/1dfbb0f868606744f84887c805b503fbfe3bef8f/Arr.php#L434

Therefore, the result trans('shop.products') returns an array and {{ trans('shop.products') }} is trying to echo array that causes the error.

**Comment by nepster-web** [comment]
my fix: https://github.com/Waavi/translation/pull/62

**Comment by nepster-web** [comment]
Waiting for your reply.

**Comment by sildraug** [comment]
@nepster-web In the pull request you sent some of the unit tests fail. Let me see if I can make it work with dot notation on the array keys.

**Comment by sildraug** [comment]
Hi @nepster-web, this should work from 2.1.5.1 onward. Sorry I didn't merge your pull request, but I needed to also update one of the tests and preferred using collection methods instead of array notation in the repo.
