### ISSUE TITLE
Mixing Waavi/translation with authentication controllers (Login & Register)

### ISSUE THREAD

**Issue by Xoshbin** [Waavi/translation#69]
Hi Guys, first thing is I'm new to Laravel. I did install Waavi/translation to my Laravel project it's working and redirects "laravel.dev:8000/en", but the route part is not working for me. I mean this part.

```
 // If the middleware is globally applied:
    Route::group(['prefix' => \UriLocalizer::localeFromRequest()], function(){
        /* Your routes here */
    });

    // For selectively chosen routes:
    Route::group(['prefix' => \UriLocalizer::localeFromRequest(), 'middleware' => 'localize')], function () {
        /* Your routes here */
    });
```

It gives me this error:

> Class 'UriLocalizer' not found

And after many trying I could fix it with Laravel's locale like that:

```
Route::get('/{locale}', function () {
    return view('welcome');
});
```

or like that:
`Route::get('/{locale}/home', 'HomeController@index');`

so where am I doing wrong? Is there anything I should do or change on this part:

```
 // If the middleware is globally applied:
    Route::group(['prefix' => \UriLocalizer::localeFromRequest()], function(){
        /* Your routes here */
    });

    // For selectively chosen routes:
    Route::group(['prefix' => \UriLocalizer::localeFromRequest(), 'middleware' => 'localize')], function () {
        /* Your routes here */
    });
```

and my real question is, How can I mix it with Laravel's default login system. I mean this:
`Auth::routes();`
I tried like that but it's not working:
`Auth::routes('/{locale});`

because now when I go to "http://laravel.dev:8000/en/login" it gives me this error:

> NotFoundHttpException in RouteCollection.php line 161:

PS: I'm using Laravel 5.3

**Comment by Xoshbin** [comment]
Well, it looks like I found a solution. I don't know if it's a good practice or no, but it's working. here is how I did:
From 

> Illuminate/Routing/Router.php

I added 

> /{locale}/ 

in front of all the routes inside _auth()_ function. just like that:

```
 public function auth()
    {
        // Authentication Routes...
        $this->get('/{locale}/login', 'Auth\LoginController@showLoginForm')->name('login');
        $this->post('/{locale}/login', 'Auth\LoginController@login');
        $this->post('/{locale}/logout', 'Auth\LoginController@logout')->name('logout');

        // Registration Routes...
        $this->get('/{locale}/register', 'Auth\RegisterController@showRegistrationForm');
        $this->post('/{locale}/register', 'Auth\RegisterController@register');

        // Password Reset Routes...
        $this->get('/{locale}/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
        $this->post('/{locale}/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
        $this->get('/{locale}/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
        $this->post('/{locale}/password/reset', 'Auth\ResetPasswordController@reset');
    }
```

I still don't know if it's right or wrong.

**Comment by sildraug** [comment]
Hi!
You need to add the UriLocalizer facade to config/app.php. The second option won't work when generating routes.
