### ISSUE TITLE
Server didn't response when using translations in blade templates

### ISSUE THREAD

**Issue by ratmir-by** [Waavi/translation#70]
Install last version (2.1.7) today, update settings, move translations to database (all moved fine), but when I try to use {{ trans('messsage') }} in blade template - page didn't response at all and get 504 Gateway Time-out error at the end. Maybe, you have an idea what it could be? I use Laravel framework v.5.3.22 Thanks!)

**Comment by ratmir-by** [comment]
Try to install all from the start on fresh laravel installation - and it workes fine. Will try install it on working project another time and try to catch the problem. I was trying to use _'mixed_db'_ mode when it break.

**Comment by ratmir-by** [comment]
The same problem on working project( 

Setting in config/translators are default, only add locales:

    'source'            => env('TRANSLATION_SOURCE', 'mixed'),
    'available_locales' => ['en', 'ru'],
    'cache'             => [
        'enabled' => env('TRANSLATION_CACHE_ENABLED', true),
        'timeout' => env('TRANSLATION_CACHE_TIMEOUT', 60),
        'suffix'  => env('TRANSLATION_CACHE_SUFFIX', 'translation'),`

I load translations to database with _php artisan translator:load_, added _Waavi\Translation\TranslationServiceProvider::class,_ instead of _Illuminate\Translation\TranslationServiceProvider::class_ and do all the same stuff like on clean laravel install before, mysql is the same, only database differs. Here is my [composer.json.txt](https://github.com/Waavi/translation/files/580124/composer.json.txt)

The only strange thing I see is Apache server work: it load my laptop for more than 30% and eat more then 2Gb of memory while trying to open the page with one translation entity (_@lang_) in blade template. But if I remove the translation - all loads in a moment.

![apache](https://cloud.githubusercontent.com/assets/1113840/20130315/1478307a-a667-11e6-80e5-065f0c7caf6d.jpg)
![504](https://cloud.githubusercontent.com/assets/1113840/20130314/1476611e-a667-11e6-8b23-a2f70467e346.jpg)

**Comment by ratmir-by** [comment]
Here is [laravel.log.txt](https://github.com/Waavi/translation/files/580311/laravel.log.txt)

**Comment by sildraug** [comment]
Hi @ratmir-by 

I've tested the package with an empty database, using the latest version, and the exact same query has you (load group "messages" for "ru" locale), and I can't get the same timeout error.

Your error log seems to point to a Database issue, since the timeout occurs in Illuminate\Database\Connection.php.

More specifically here:

```php
/**
     * Run a SQL statement.
     *
     * @param  string    $query
     * @param  array     $bindings
     * @param  \Closure  $callback
     * @return mixed
     *
     * @throws \Illuminate\Database\QueryException
     */
    protected function runQueryCallback($query, $bindings, Closure $callback)
    {
        // To execute the statement, we'll simply call the callback, which will actually
        // run the SQL against the PDO connection. Then we can calculate the time it
        // took to execute and log the query SQL, bindings and time in our memory.
        try {
            $result = $callback($this, $query, $bindings);
        }

        // If an exception occurs when attempting to run a query, we'll format the error
        // message to include the bindings with SQL, which will make this exception a
        // lot more helpful to the developer instead of just the database's errors.
        catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }

        return $result;
    }

````

This doesn't seem to be an issue with Laravel or this package, but rather your Database is timing out for some reason.

Best,
