### ISSUE TITLE
translation source set to database, still translating from the files

### ISSUE THREAD

**Issue by nermion** [Waavi/translation#73]
I set TRANSLATION_SOURCE to database

and when I do this

trans('pagination.previous');

it get's translation from the file instead of database. 

I made a video to show the bug
https://www.youtube.com/watch?v=xrtmxldUvcs

Laravel Framework version 5.3.22
"waavi/translation": "2.1.x"

**Comment by nermion** [comment]
solved

**Comment by mlinko** [comment]
I have this problem too. how did you solve it?

**Comment by nermion** [comment]
By flushing laravel config cache
