### ISSUE TITLE
Ensuring that all translations are available

### ISSUE THREAD

**Issue by GeekTNTdotCom** [Waavi/translation#79]
Is there a way to ensure that every item is translated into all languages (especially when adding a new language)?

If an translation for an item in Spanish is missing will it return English or it will return blank?

Thanks!

**Comment by sildraug** [comment]
@GeekTNTdotCom There is noe way to ensure every item is translated, but on 2.2 you can use Waavi\Translation\Repositories\LanguageRepository@percentTranslated to check how much of a given locale has been translated.

For example, given 'en' is the default locale:

```php
App::make('Waavi\Translation\Repositories\LanguageRepository')->percentTranslated('es');
```

Will return a number between 0 and 100 representing the percentage of entries translated in Spanish.

When an entry is not found for a given language, the one available for the default one is returned instead.
