### ISSUE TITLE
Change the default source 

### ISSUE THREAD

**Issue by mifas** [Waavi/translation#82]
I'm using Laravel 5.3 When I fresh install the package, then I getting translator_translations table not found. Please change the default source value to files.  Then only I can run artisan or any other console base commands. 

BTW  I'm handling multi-tenant database, and tenant database connection set by middleware.

**Comment by przemoli** [comment]
I can confirm that issue is still there.
#104

**Comment by sildraug** [comment]
@mifas @przemoli 
Please check version 2.2.2, it should be fixed.
