### ISSUE TITLE
Installatio error: FileLoader conatins 1 abstract method

### ISSUE THREAD

**Issue by maig81** [Waavi/translation#83]
I installed fresh installation of Laravel 5.4, and before anything else tried to install Waavi/translation. 
Installation went OK, I have updated the config/app.php, and on "php artisan config:cache" i get error

> [Symfony\Component\Debug\Exception\FatalErrorException]
> Class Waavi\Translation\Loaders\FileLoader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Translation\LoaderInterface::namespaces)

Any ideas?

**Comment by ftob** [comment]
Exactly the same error.

**Comment by ftob** [comment]
Need update to version "waavi/translation": "2.2.x". Resolve
