### ISSUE TITLE
How to set database connection? 

### ISSUE THREAD

**Issue by ersoypembe** [Waavi/translation#88]
Hi;

Let's say I have multiple customer_a, customer_b, customer_c etc databases and a master database (administrator). I want to use only administrator database to have translation tables instead of creating migrations for each customer.

I checked source code $this->database is set to $app['db'] -- is there a way to override connection or config to set database connection  ?

**Comment by sildraug** [comment]
Hi,

Right now there is no way of configuring that, but we would welcome a pull request to add that feature!

**Comment by ersoypembe** [comment]
Hi;

I reviewed the package and found some ways to implement it. In my opinion, the best approach is to set connection in Translation and Language models. 

We can't set 

`protected $connection = $app['config']->get('translator.connection');` 

so I tried to override constructor like this.

```
   /**
     * Translation constructor.
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setConnection($app['config']->get('translator.connection'));
    }
```

**Comment by ersoypembe** [comment]
Hi;

I will send a PR when i find some time. I reviewed the code and found multiple places to re-implement some structures (models, migrations, validations (unique table name etc)). Thank you for your reply.
