### ISSUE TITLE
Basic usage guide

### ISSUE THREAD

**Issue by octolit** [Waavi/translation#93]
Could you please extend basic usage guide? I have successfully installed, migrated and loaded languages. However using

`{{ trans('validations.accepted') }}`

only gives the string **validations.accepted**

not sure (as Laravel newbie) what am i missing.

**Comment by joy014** [comment]
When you get the exact namespaced key in the trans() function, it means that the translation for the key doesnt exist in the current language. Create it and the key will be replaced with the actual text.
