### ISSUE TITLE
Navigating from page to page, looses the locale setting

### ISSUE THREAD

**Issue by DilithiumVentures** [Waavi/translation#94]
Hi i am using Laravel 5.4 and implemented the examples, this works like a charm. Thanks!
One thing doesn't work though and this topic sounds very similar, but doesn't state a solution :-)

Once i change the url to /nl from /en it will load the correct language on the page. But as soon as i navigate to another page, this locale is lost and it defaults back to /en. I have implemented the code, according to the manual, but this doesn't work (and the language switcher throws an exception too).

It feels like the session is non-persistent or something, should it keep track of the locale by default? Or do i need to set it somewhere?

**Comment by odat** [comment]
In Kernel.php add in middleware :  
`        \Illuminate\Session\Middleware\StartSession::class,
`
```
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Waavi\Translation\Middleware\TranslationMiddleware::class,
    ];
```

**Comment by sildraug** [comment]
@odat Thank you for helping out 👍
