### ISSUE TITLE
Model attributes translation 

### ISSUE THREAD

**Issue by emildd** [Waavi/translation#98]
how can I use this translation with this method ?
I've tried this step
class Example extends Model
	{
	    use Waavi\Translation\Traits\Translatable;
	    protected $translatableAttributes = ['title', 'text'];
	}

how can I get 'title' object with translate or original value?

**Comment by sildraug** [comment]
If you want the original value, you can do $example->rawTitle

**Comment by abbood** [comment]
@sildraug what if i want the translated title?
